% BBA
% 
%   Contents file for BBA and its subfolders.
%   
%   BBA
%   BBA.mlapp
%   BBA.mltbx
%   BBA.prj
%   Copy_of_Contents     - BBA
%   demo                 - FILE
%   README.md
%   testBBA              - Runtests('testMain.m')
%   尚需完善 README.txt
%   
%   BBA\BBARELEASE
%   BBA190213 V108.mltbx
%   BBA190213 V109.mltbx
%   BBA190214 V110.mltbx
%   BBA190219 V115.mltbx
%   BBA190219 V118.mltbx
%   
%   BBA\CHECK
%   chkInput             - GCHECKINPUT 重要函数:输入数据da转换(不增加新数据）+输入数据da核对
%   chkLUnewold          - 每次RunAlgorithm后，判断d.LU 输入与输出的差距
%   chkStrip             - Strip结构体核对
%   chktLU               - 功能：核验是否数据是上轻下重；是否Z高度与ItemSEQ一致；是否ITEMID与XY坐标一致;
%   InitializeInputData  - V2 - 不含Random算例
%   InitializeParameter  - Initialize the parameter data structure
%   InitializeRandomData - ==> 初始化随机生成数据
%   isMixedStrip         - 函数3: 判断STRIP是否混合型isMixedStrip
%   isrepeated           - 判定在同一fatherid下, id是否重复
%   isSameCol            - 判断结构体s是否全部相同列的矩阵构成
%   isUpDownWeight       - 判定在同一Item下, 是否上轻下重
%   plotcube             - - Display a 3D-cube in the current axes
%   plotSolutionT        - ==> 作图LU/STRIP/BIN
%   
%   BBA\FUN
%   BBA_Main             - 前4个必须
%   Copy_of_HStripToBin  - 重要函数:Strip放入Bin中 %  行数:长宽高(row);  列数:托盘数量(coloum);
%   cpuBin               - GET BIN 相关属性 isTileNeed
%   cpuItem              - GET ITEM 相关属性
%   cpuLU_del            - CpuLU ==> 获取LU的isNonMixed和LU的isMixedTile
%   cpuStrip             - GET STRIP 相关属性
%   cpuStrip_del         - GET STRIP 相关属性
%   cpuStripnbItem       - GET STRIP 相关属性
%   cpuVehLU             - 重要函数:
%   getBBASeqTLU         - 1 Table排序 : TLUsorted %基本前两行排序就已经定了 BINSEQ一定固定的，只是ShowSEQ分步骤而已
%   getLuRotaedBBA       - ==> 更新LU的Rotaed标记( LU横放或竖放 却决于距离边界的宽度 哪个小选哪个
%   getOrderofLID        - V5 : 增加可读性 V4 含EID且数据结构基本重写
%   getOrderofSID        - V4 : SID is cell方式 且分开ITEM和STRIP两类 重点排除order被重复赋值的情况
%   getPartDinThisBin    - ==> GET 结构体d中的属于本bin的部分数据
%   getReorderStruct     - 动态数组并排序
%   getReviseID          - 在同一fatherid下,确定重复时，改变当下id与其他重复的数字,
%   getStripnID          - 通过LU计算：Strip对应的LUID数量、Strip对应相应bin内的ID数量
%   getSturctT           - 转变为struct为table
%   getTableLU           - 转变为Table: TLU
%   HBinChange           - ==> 更换车型
%   HBinCombine          - ==> 对原始 改变车型 平铺 混合间隙 后的结果进行合并
%   HBinGapAdjust        - ==> Gap Adjust for Each Bin
%   HBinpingpu           - V2
%   HBinpingpu_del       - HBinpingpu ==> 从输入数据maind，主输出数据do，参数p 获取整车平铺do3Array/甩尾平铺do2Array的输出数据
%   HItemToBin           - V2
%   HItemToStrip         - 重要函数:Item放入Strip中 %  行数:长宽高(row);  列数:托盘数量(coloum);
%   HLUtoItem            - 重要函数:LU堆垛后形成Item %  行数:长宽高(row);  列数:托盘数量(coloum);
%   HStripBalance_del    - 函数: Strip均衡
%   HStripSW             - 函数: Strip甩尾 v3 增大甩尾范围
%   HStripToBin          - 重要函数:Strip放入Bin中 %  行数:长宽高(row);  列数:托盘数量(coloum);
%   HStripToBinAgain     - 函数1: 量大车头方案2: V3: 基本未动
%   LWHbuffer            - Add LWH的buffer 且增加旋转状态
%   LWHunbuffer          - Remove LWH的buffer 且恢复旋转状态
%   LWHunbufferCoord     - Update LWH的CoordLUBin 考虑margin 不考虑旋转
%   pgRectangle          - 由四要素获取四个顶点
%   pgStripLU            - 由Strip的序列号idxs,获取LU表格中对应的pgon
%   repairItems          - 函数1 : isWeightFine: 判断LU是否上轻下重构成
%   RunAlgorithm         - 重新执行HStripToBin方案
%   setLCwithoutbuff     - ==> 更新 LWH and Coord 不含margin of LU and Item
%   setLULWHwithbuff     - ==> 修订LU的LWH数据 包含margin 考虑Rotaed
%   
%   BBA\NEW
%   BBA_Main_190216.jar
%   
%   BBA\READEME
%   BBA版本1102
%   BBA版本MilkRun1108
%   
%   BBA\TEST
%   Copy_2_of_test_main  - 测试函数:调用主函数
%   Copy_3_of_test_main  - 测试函数:调用主函数
%   Copy_4_of_test_main  - 测试函数:调用主函数
%   Copy_of_test_main    - 测试函数:调用主函数
%   Copy_of_test_main_Mr - 测试函数:调用主函数
%   
%   BBA\UTILITY
%   comp_struct          - Check two structures for differances - i.e. see if strucutre s1 == structure s2
%   getContents          - Get the contents of a specified directory
%   list_struct          - List the contents of a structure
%   NewFigure            - Create a new named figure window
%   padcat               - - concatenate vectors with different lengths by padding with NaN
%   PlotSet              - Create two-dimensional plots from a data set
%   printstruct          - 网络函数:输出结构体
%   updateContents       - Create a Contents.m file including subdirectories
%    
%   This file was generated by updateContents.m on 21 Feb 2019 at 16:39:05.
